# ------ root_path/dataset_name ------
root_path: '/root'  # 设置为你的数据集根目录路径


# ------ Load Cache and Features ------
load_cache: False  # 不加载缓存，除非有预计算的缓存数据
load_pre_feat: False  # 不加载预计算的特征

# 如果你以后有预先计算好的缓存或特征，你可以设置为True：
# load_cache: True
# load_pre_feat: True


# ------ Hyperparameters ------
search_hp: True  # 启用超参数搜索
# 如果你不需要超参数搜索，可以将其设置为False
# search_hp: False

# 设置搜索的范围和步长
search_scale: [50, 50] #较好的tip无f
search_step: [200, 20]
# search_scale: [100, 100]
# search_step: [400, 200]

init_beta: 1  # 模型的初始beta值
init_alpha: 10  # 模型的初始alpha值


# ------ Basic Config ------
dataset: 'breakhis'  # 自定义数据集名称
shots: -1  # 使用全量数据集，若要进行少样本学习，可以将其设置为具体的样本数，如shots: 16
backbone: 'RN50'  # 使用ResNet-50作为骨干网络

lr: 0.001  # 学习率
augment_epoch: 1  # 数据增强的训练周期数
train_epoch: 50  # 总的训练周期数
